### ISSUE TITLE
usb-monitor hanges up the program when stop_monitoring is called

### ISSUE THREAD

**Issue by dmitrij9992905** [Eric-Canas/USBMonitor#5]
Hello!

I needed to stop USB devices monitoring if not needed. But if I call stop_monitoring after start_monitoring, then main program is blocked with stop_monitoring

Python 3.10 is used and Ubuntu Linux 22.04

**Comment by Eric-Canas** [comment]
Hi! Thanks a lot @dmitrij9992905. 

I have been able to reproduce and fix the bug! 

If you `pip install --upgrade usb-monitor` it should be solved.

Sorry for the inconvenience and thanks again!! ^~^
