### ISSUE TITLE
device_info_str is not defined

### ISSUE THREAD

**Issue by ghost** [Eric-Canas/USBMonitor#9]
I could helped noticed that my linter is highlighting that "device_info_str is not defined" as you can see by my piece of my code in the print below. Any ideas what it might be the cause??

![Captura de tela 2024-11-07 211859](https://github.com/user-attachments/assets/5a8d0113-6026-4933-a712-0e04fd4b9c4d)

**Comment by Eric-Canas** [comment]
That device_info_str is a testing function defined in the example of the readme, not a part of the library. Maybe you forgot to define it on your test code?

```Python
device_info_str = lambda device_info: f"{device_info[ID_MODEL]} ({device_info[ID_MODEL_ID]} - {device_info[ID_VENDOR_ID]})"
# Define the `on_connect` and `on_disconnect` callbacks
on_connect = lambda device_id, device_info: print(f"Connected: {device_info_str(device_info=device_info)}")
on_disconnect = lambda device_id, device_info: print(f"Disconnected: {device_info_str(device_info=device_info)}")
```
